### ISSUE TITLE
401 Unauthorized错误

### ISSUE THREAD

**Issue by cuichacha** [khassar00/ktor-markdown-yuque#1]
项目可以运行，但是报了个错，如图。
<img width="1192" alt="Screen Shot 2021-01-18 at 10 22 33" src="https://user-images.githubusercontent.com/12711401/104867893-e18f1700-597c-11eb-8d94-502af555d30d.png">
貌似是访问被阻止了，不知道是不是我把token搞错了，我用的token是这里的ctoken。
<img width="975" alt="Screen Shot 2021-01-18 at 11 04 57" src="https://user-images.githubusercontent.com/12711401/104867992-1c914a80-597d-11eb-9865-4860ceb61cc8.png">

**Comment by khassar00** [comment]
需要访问官网申请https://www.yuque.com/settings/tokens
